INSERT INTO TB_NOTIFICACAO(NOME_REMETENTE, TITULO, STATUS) VALUES ('Teste 123', 'Teste envio 123', 'SUCESSO');
INSERT INTO TB_NOTIFICACAO(NOME_REMETENTE, TITULO, STATUS) VALUES ('Teste 321', 'Teste envio 321', 'SUCESSO');
INSERT INTO TB_NOTIFICACAO(NOME_REMETENTE, TITULO, STATUS) VALUES ('Teste 111', 'Teste envio 444', 'SUCESSO');
INSERT INTO TB_NOTIFICACAO(NOME_REMETENTE, TITULO, STATUS) VALUES ('Teste 222', 'Teste envio 555', 'SUCESSO');
INSERT INTO TB_NOTIFICACAO(NOME_REMETENTE, TITULO, STATUS, DATA_ATUAL_ERRO, DESCRICAO_ERRO) VALUES ('Teste 555', 'Teste envio 668', 'FALHA', NOW(), 'Erro');