server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: produtos-service
            uri: lb://PRODUTOS
            predicates:
              - Path=/api-produtos/**
          - id: notificacao-service
            uri: lb://NOTIFICACAO
            predicates:
              - Path=/api-notificacao/**

produtos:
  service:
    registry:
      username: serviceregistry
      password: produtos123sr

eureka:
  client:
    service-url:
      defaultZone: 'http://${produtos.service.registry.username}:${produtos.service.registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

